on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test
        id: test
        uses: 0xchina/test-mosquitto@master
        with:
          config: ${{ github.workspace }}/mosquitto.conf

