on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test
        id: test
        uses: 0xchina/test-mosquitto@master
      - name: Upload files
        run: |
          apt install -y mosquitto-clients
          mosquitto_pub -h localhost -u apsu -P yangpaopao -t test -m "test"
